import { VisualizerSettings, AudioMappings } from './types';

export interface Preset {
  id: string;
  name: string;
  description: string;
  settings: Partial<VisualizerSettings>;
}

const DEFAULT_MAPPINGS: AudioMappings = {
  velocity: 'mid',
  density: 'bass',
  color: 'treble',
  rotation: 'none',
};

export const PRESETS: Preset[] = [
  {
    id: 'classic',
    name: 'Classic Light Show',
    description: 'Slow, luminous blobs of amber, magenta and ultramarine drift and merge in a round dish: the 1960s overhead projector.',
    settings: {
      globalSpeed: 0.00924,
      surge: 0.5,        // unhurried, dreamlike pace
      layerCount: 2,
      blendMode: 'screen',       // additive glow — colors brighten where they overlap
      gooeyEffect: 0.65,         // organic, rounded blob edges
      rotationSpeed: 0.008,      // barely perceptible rotation keeps it alive
      centerGravity: 0.12,       // gentle inward drift prevents edge stagnation
      ledPlatform: false,
      diffusionRate: 0,          // measured: the bleed cost more edge than it bought
      buoyancy: 0.4,             // moderate rise — not too static, not too chaotic
      advection: 0.35,           // smooth transport, no turbulence
      damping: 0.988,            // very slow energy loss — movements persist gracefully
      heatDecay: 0.992,          // warmth lingers, keeps gentle convection going
      automateRate: 0.15,        // regular auto-injection keeps the frame alive
      platePressure: 0.25,       // subtle radial spread from center
      glassSmear: 0.3,           // soft smearing, no harsh edges
      rainDrip: 0.15,            // occasional downward streaks for variety
      viscosity: 'thick',        // heavy, syrupy movement
      polarity: 0.7,             // colors stay distinct but can gently intermingle
      evaporationRate: 0.005,    // colors persist a long time
      airVelocity: 0.04,         // near-still air — no turbulence
      vibrationFrequency: 0.08,  // minimal vibration — serene
      audioImpact: 0.55,         // audible music visibly drives the fluid
      turbulenceScale: 0.5,      // lively multi-scale ripple
      turbulenceDetail: 3,
      blobSurfaceTension: 0.35,  // loose amoeba shapes, slow pinch-and-merge
      boundaryContrast: 0.5,     // bright line where dyes meet
      saturationBoost: 1.45,
      glossiness: 0.0,           // flat backlit dye — the projector look
      postBlurRadius: 0.35,
      dishVignette: 0.35,
      lampWarmth: 0.15,
      secondLamp: 0.2,
      audioMappings: {
        velocity: 'bass',        // low frequencies push the fluid gently
        density: 'volume',       // louder = more color, but mapped gently
        color: 'treble',         // high frequencies shift hue — sparkle
        rotation: 'none',        // no audio-driven rotation — keep it calm
      },
    }
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    description: 'Spiral arms of starlight swirl through the void — galaxies colliding in slow motion.',
    settings: {
      globalSpeed: 0.00756,
      surge: 0.5,        // stately cosmic drift
      layerCount: 2,
      blendMode: 'lighter',      // additive light — stars brighten where they overlap
      gooeyEffect: 0.15,         // low goo — sharper points of light, less blobby
      rotationSpeed: 0.035,      // visible rotation creates spiral arms
      centerGravity: 0.85,       // strong pull inward — matter orbits a galactic core
      ledPlatform: true,
      diffusionRate: 0.00004,    // extremely low — pinpoints of light stay sharp
      buoyancy: 0.25,            // minimal buoyancy — horizontal swirl dominates
      advection: 0.75,           // strong transport — sweeping spiral arm motion
      damping: 0.994,            // very high — movements persist, orbits sustain
      heatDecay: 0.998,          // heat lingers forever — nebula glow persists
      automateRate: 0.14,        // moderate injection — periodic star bursts
      platePressure: 0.1,        // minimal plate spread — gravity dominates
      glassSmear: 0.15,          // light smearing — comet-tail streaks
      rainDrip: 0.0,             // no dripping — weightless space
      viscosity: 'thin',         // thin — fluid fragments into filaments and streams
      polarity: 0.25,            // low — colors intermingle freely like nebula gas
      evaporationRate: 0.002,    // stars persist for a very long time
      airVelocity: 0.02,         // near-vacuum — no turbulence
      vibrationFrequency: 0.0,   // no vibration — serene void
      audioImpact: 0.4,
      turbulenceScale: 0.55,     // strong swirl — spiral arms shear and stretch
      turbulenceDetail: 4,       // fine filament detail down to star-cluster scale
      blobSurfaceTension: 0.1,   // near-zero cohesion — matter fragments freely
      boundaryContrast: 0.25,
      saturationBoost: 1.45,     // vivid nebula color
      glossiness: 0.0,
      postBlurRadius: 0.2,       // very sharp — pinpoints of light stay pinpoints
      ledMode: 'single',
      ledColor: '#03041a',
      ledSpeed: 0.0,
      secondLamp: 0.25,
      audioMappings: {
        velocity: 'bass',        // bass drives galactic tides
        density: 'energy',       // overall energy triggers star formation
        color: 'treble',         // treble shifts nebula hue
        rotation: 'energy',      // energy modulates orbital speed
      },
    }
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    description: 'Slow, dense teal and midnight fluids drift down through a deep blue LED platform, light coming through them from below.',
    settings: {
      globalSpeed: 0.0126,
      surge: 0.22,
      layerCount: 2,
      blendMode: 'overlay',
      gooeyEffect: 0.8,
      rotationSpeed: 0.01,
      centerGravity: 0.8,
      ledPlatform: true,
      ledMode: 'ocean',
      ledSpeed: 0.05,
      diffusionRate: 0.0001,
      buoyancy: 0.2,
      advection: 0.2,
      damping: 0.99,
      heatDecay: 0.98,
      automateRate: 0.05,
      platePressure: 0.1,
      glassSmear: 0.2,
      rainDrip: 0.8,
      viscosity: 'thick',
      polarity: 0.8,
      evaporationRate: 0.01,
      airVelocity: 0.05,
      vibrationFrequency: 0.2,
      transmission: 0.85,
      secondLamp: 0.3,
      saturationBoost: 1.35,
      audioMappings: {
        velocity: 'volume',
        density: 'bass',
        color: 'none',
        rotation: 'energy',
      },
    }
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'High contrast, fast-moving neon fluids over a cyberpunk LED base.',
    settings: {
      globalSpeed: 0.0336,
      postBlurRadius: 0.1,
      boundaryContrast: 0.7,
      beads: 0.35,
      surge: 0.85,
      layerCount: 2,
      blendMode: 'lighter',
      gooeyEffect: 0.1,
      rotationSpeed: 0.05,
      centerGravity: 0.5,
      ledPlatform: true,
      ledMode: 'cyberpunk',
      ledSpeed: 0.3,
      diffusionRate: 0.0002,
      buoyancy: 0.8,
      advection: 0.6,
      damping: 0.95,
      heatDecay: 0.9,
      automateRate: 0.2,
      platePressure: 0.6,
      glassSmear: 0.8,
      rainDrip: 0.2,
      viscosity: 'thin',
      polarity: 0.2,
      evaporationRate: 0.05,
      airVelocity: 0.3,
      vibrationFrequency: 0.8,
      chromaticAberration: 0.35,
      audioMappings: {
        velocity: 'energy',
        density: 'treble',
        color: 'timbre',
        rotation: 'complexity',
      },
    }
  },
  {
    id: 'lava-lamp',
    name: 'Lava Lamp',
    description: 'Amber and red wax rises and sinks through violet liquid: heavy blobs that stretch, pinch off and fall back.',
    settings: {
      globalSpeed: 0.0168,
      surge: 0.4,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 1,
      rotationSpeed: 0.01,
      centerGravity: 0,          // the wax wanders the lamp; the music already pours it in the middle
      ledPlatform: true,
      ledMode: 'single',         // one dim ember under the whole lamp, not a colour wheel
      ledColor: '#2a0620',
      ledSpeed: 0.02,
      diffusionRate: 0.00005,
      buoyancy: 0.9,
      advection: 0.15,
      damping: 0.97,
      heatDecay: 0.99,
      automateRate: 0.1,
      platePressure: 0.2,
      glassSmear: 0.3,
      rainDrip: 0.1,
      viscosity: 'thick',
      polarity: 0.95,
      evaporationRate: 0.02,
      airVelocity: 0.05,
      vibrationFrequency: 0.1,
      turbulenceScale: 0.05,     // lava moves as whole blobs: no ripple to tear their edges
      turbulenceDetail: 2,
      blobSurfaceTension: 1,     // as round as the plate will hold them
      boundaryContrast: 0.3,
      saturationBoost: 1.3,
      glossiness: 0.3,           // a wax sheen, the one look that earns one
      edgeRelief: 0.6,           // and a rim, so a blob reads as a body rather than a stain
      // The liquid is clear and the wax is not. A full plate is a red wash (which is
      // what this look was with music on): at 0.45 the wax has somewhere to be, and
      // the exposure keeps the thin film between blobs as the liquid, not a tint.
      dyeBudget: 0.45,
      exposure: 0.9,
      postBlurRadius: 0.55,      // softer edges than the flat-dye presets
      lampWarmth: 0.4,
      transmission: 0.75,
      audioMappings: {
        velocity: 'bass',
        density: 'volume',
        color: 'none',
        rotation: 'none',
      },
    }
  },
  {
    id: 'acid-trip',
    name: 'Acid Trip',
    description: 'Clashing ultramarine, coral, lime and magenta under a turning colour gel: everything inverts where it overlaps.',
    settings: {
      globalSpeed: 0.0336,
      beads: 0.4,
      surge: 0.95,
      layerCount: 2,
      blendMode: 'exclusion',
      gooeyEffect: 0.3,
      rotationSpeed: 0.1,
      centerGravity: 0.6,
      ledPlatform: true,
      ledMode: 'rainbow',
      ledSpeed: 0.4,
      diffusionRate: 0.0002,
      buoyancy: 0.6,
      advection: 0.8,
      damping: 0.95,
      heatDecay: 0.97,
      automateRate: 0.25,
      platePressure: 0.8,
      glassSmear: 0.9,
      rainDrip: 0.4,
      viscosity: 'thin',
      polarity: 0.5,
      // It lays dye on the weakest thing the music does (timbre) and dried it at
      // 0.04, so with a band playing the plate ran empty and the frame was the
      // bare LED wheel. It holds its dye now, and the wheel shows through it.
      evaporationRate: 0.02,
      dyeBudget: 0.6,
      audioImpact: 0.8,
      airVelocity: 0.5,
      vibrationFrequency: 0.9,
      turbulenceScale: 0.8,      // maximum chaos — ripples on ripples
      turbulenceDetail: 4,
      blobSurfaceTension: 0.15,  // shapes constantly tear and reform
      edgeRelief: 0.65,
      bubbles: 0.17,
      boundaryContrast: 0.75,     // hard psychedelic color interfaces
      saturationBoost: 1.6,      // hyper-saturated
      glossiness: 0.0,
      postBlurRadius: 0.12,
      gelWheel: 0.55,
      gelSpeed: 0.6,
      audioMappings: {
        velocity: 'treble',
        density: 'timbre',
        color: 'complexity',
        rotation: 'energy',
      },
    }
  },
  {
    id: 'bass-drop',
    name: 'Bass Drop',
    description: 'Every bass hit drops a heavy splash from height: crimson and ultramarine thrown across ice, the plate squeezed on the kick.',
    settings: {
      globalSpeed: 0.021,
      beads: 0.25,
      surge: 0.9,
      layerCount: 2,
      blendMode: 'lighter',
      gooeyEffect: 0.6,
      rotationSpeed: 0.01,
      centerGravity: 0.4,
      ledPlatform: false,
      diffusionRate: 0.0002,
      buoyancy: 0.3,
      advection: 0.5,
      damping: 0.94,
      heatDecay: 0.92,
      automateRate: 0.05,
      platePressure: 0.9,
      glassSmear: 0.7,
      rainDrip: 0.3,
      viscosity: 'thick',
      polarity: 0.7,
      evaporationRate: 0.02,
      airVelocity: 0.2,
      vibrationFrequency: 1.0,
      dropHeight: 0.9,
      beatSqueeze: 0.8,
      audioMappings: {
        velocity: 'bass',
        density: 'bass',
        color: 'none',
        rotation: 'none',
      },
    }
  },
  {
    id: 'timbre-shifter',
    name: 'Timbre Shifter',
    description: 'The brightness of the sound controls the color and rotation of the fluid.',
    settings: {
      globalSpeed: 0.0252,
      surge: 0.55,
      layerCount: 2,
      blendMode: 'lighter',
      gooeyEffect: 0.3,
      rotationSpeed: 0.03,
      centerGravity: 0.5,
      ledPlatform: true,
      ledMode: 'rainbow',
      ledSpeed: 0.2,
      diffusionRate: 0.0001,
      buoyancy: 0.7,
      advection: 0.6,
      damping: 0.98,
      heatDecay: 0.96,
      automateRate: 0.15,
      platePressure: 0.4,
      glassSmear: 0.5,
      rainDrip: 0.6,
      viscosity: 'thin',
      polarity: 0.6,
      evaporationRate: 0.03,
      airVelocity: 0.1,
      vibrationFrequency: 0.4,
      hueJourney: 6,
      audioMappings: {
        velocity: 'mid',
        density: 'volume',
        color: 'timbre',
        rotation: 'timbre',
      },
    }
  },
  {
    id: 'boiling-point',
    name: 'Boiling Point',
    description: 'A cauldron at the boil: bubbles rise and break through lime, jade and gold, and the heat churns the whole pot.',
    settings: {
      globalSpeed: 0.0294,
      beads: 0.35,
      surge: 0.85,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.7,
      rotationSpeed: 0.02,
      centerGravity: 0.1,
      ledPlatform: true,
      ledMode: 'single',
      ledSpeed: 0.0,
      diffusionRate: 0.0002,
      buoyancy: 1.0,
      advection: 0.8,
      damping: 0.9,
      heatDecay: 0.99,
      automateRate: 0.2,
      platePressure: 0.5,
      glassSmear: 0.6,
      rainDrip: 0.7,
      viscosity: 'thin',
      polarity: 0.8,
      // The fire wheel with nothing on it, under music: 0.06 dried the plate
      // faster than the pour filled it, and the pour follows complexity, which
      // read two percent of its range until the analyser was fixed.
      evaporationRate: 0.025,
      dyeBudget: 0.6,
      audioImpact: 0.8,
      airVelocity: 0.4,
      vibrationFrequency: 0.7,
      ledColor: '#081604',
      bubbles: 0.85,
      dropHeight: 0.7,
      saturationBoost: 1.4,
      audioMappings: {
        velocity: 'energy',
        density: 'complexity',
        color: 'treble',
        rotation: 'complexity',
      },
    }
  },
  {
    id: 'microscopic-chaos',
    name: 'Microscopic Chaos',
    description: 'A stained slide on a bright field: magenta, violet and blue cells crowd, divide and jostle under the lamp.',
    settings: {
      globalSpeed: 0.0168,
      boundaryContrast: 0.7,
      beads: 0.45,
      surge: 0.9,
      layerCount: 2,
      blendMode: 'multiply',
      gooeyEffect: 0.15,
      rotationSpeed: 0.01,
      centerGravity: 0.5,
      ledPlatform: true,
      ledMode: 'single',
      ledSpeed: 0.0,
      diffusionRate: 0.00005,
      buoyancy: 0.4,
      advection: 0.3,
      damping: 0.98,
      heatDecay: 0.95,
      automateRate: 0.3,
      platePressure: 0.8,
      glassSmear: 0.2,
      rainDrip: 0.1,
      viscosity: 'thick',
      polarity: 0.95,
      evaporationRate: 0.01,
      airVelocity: 0.1,
      vibrationFrequency: 0.6,
      ledColor: '#f1ebf5',
      cells: 0.45,
      saturationBoost: 1.15,
      dyeBudget: 0.55,
      audioMappings: {
        velocity: 'complexity',
        density: 'energy',
        color: 'timbre',
        rotation: 'none',
      },
    }
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    description: 'Curtains of jade, lime and lavender ripple across a night sky, slow and hushed.',
    settings: {
      globalSpeed: 0.0105,
      surge: 0.2,
      layerCount: 2,
      blendMode: 'lighter',
      gooeyEffect: 0.6,
      rotationSpeed: 0.008,
      centerGravity: 0.05,
      ledPlatform: true,
      ledMode: 'single',
      ledSpeed: 0.0,
      diffusionRate: 0.0002,
      buoyancy: 0.65,
      advection: 0.35,
      damping: 0.985,
      heatDecay: 0.99,
      automateRate: 0.06,
      platePressure: 0.15,
      glassSmear: 0.4,
      rainDrip: 0.2,
      viscosity: 'thin',
      polarity: 0.4,
      evaporationRate: 0.008,
      // Curtains, not a sheet: a full plate on the lighter blend was one flat
      // green. With less dye and the thin film read as sky, the ocean lamp
      // shows between the folds.
      dyeBudget: 0.35,
      exposure: 0.5,
      airVelocity: 0.08,
      vibrationFrequency: 0.15,
      ledColor: '#020818',
      secondLamp: 0.35,
      audioMappings: {
        velocity: 'bass',
        density: 'volume',
        color: 'complexity',
        rotation: 'energy',
      },
    }
  },
  {
    id: 'solar-flare',
    name: 'Solar Flare',
    description: 'Explosive plumes of plasma erupt from a white-hot core, driven by bass.',
    settings: {
      globalSpeed: 0.0252,
      boundaryContrast: 0.55,
      beads: 0.3,
      surge: 0.8,
      layerCount: 2,
      blendMode: 'lighter',
      gooeyEffect: 0.3,
      rotationSpeed: 0.015,
      centerGravity: 0.7,
      ledPlatform: true,
      ledMode: 'fire',
      ledSpeed: 0.15,
      diffusionRate: 0.0002,
      buoyancy: 0.85,
      advection: 0.7,
      damping: 0.93,
      heatDecay: 0.97,
      automateRate: 0.18,
      platePressure: 0.7,
      glassSmear: 0.6,
      rainDrip: 0.05,
      viscosity: 'thin',
      polarity: 0.3,
      evaporationRate: 0.04,
      airVelocity: 0.35,
      vibrationFrequency: 0.6,
      iridescence: 0.25,
      audioMappings: {
        velocity: 'bass',
        density: 'energy',
        color: 'treble',
        rotation: 'bass',
      },
    }
  },
  {
    id: 'jellyfish-bloom',
    name: 'Jellyfish Bloom',
    description: 'Translucent magenta and lavender bells pulse through teal water, lit from beneath.',
    settings: {
      globalSpeed: 0.0126,
      surge: 0.25,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.85,
      rotationSpeed: 0.006,
      centerGravity: 0.15,
      ledPlatform: true,
      ledMode: 'ocean',
      ledSpeed: 0.04,
      diffusionRate: 0.00008,
      buoyancy: 0.55,
      advection: 0.25,
      damping: 0.988,
      heatDecay: 0.995,
      automateRate: 0.08,
      platePressure: 0.25,
      glassSmear: 0.15,
      rainDrip: 0.45,
      viscosity: 'thick',
      polarity: 0.85,
      evaporationRate: 0.005,
      airVelocity: 0.04,
      vibrationFrequency: 0.25,
      transmission: 0.3,
      secondLamp: 0.3,
      audioMappings: {
        velocity: 'mid',
        density: 'mid',
        color: 'timbre',
        rotation: 'none',
      },
    }
  },
  {
    id: 'fractal-dream',
    name: 'Fractal Dream',
    description: 'The plate folded into a turning six-way mirror: rings of amber, magenta and teal become a mandala that breathes with the music.',
    settings: {
      globalSpeed: 0.0189,
      boundaryContrast: 0.6,
      beads: 0.3,
      surge: 0.8,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.2,
      rotationSpeed: 0.04,
      centerGravity: 0.9,
      ledPlatform: false,
      ledMode: 'single',
      ledSpeed: 0.0,
      diffusionRate: 0.0002,
      buoyancy: 0.5,
      advection: 0.55,
      damping: 0.96,
      heatDecay: 0.96,
      automateRate: 0.2,
      platePressure: 0.5,
      glassSmear: 0.7,
      rainDrip: 0.3,
      viscosity: 'thin',
      polarity: 0.65,
      evaporationRate: 0.025,
      airVelocity: 0.25,
      vibrationFrequency: 0.55,
      kaleidoscope: 6,
      kaleidoSpin: 0.06,
      kaleidoZoom: 0.85,
      ledColor: '#000000',
      saturationBoost: 1.45,
      dishVignette: 0.5,
      audioMappings: {
        velocity: 'complexity',
        density: 'mid',
        color: 'timbre',
        rotation: 'treble',
      },
    }
  },
  {
    id: 'velvet-underground',
    name: 'Velvet Underground',
    description: 'Rich pools of magenta and raspberry over midnight, churning slowly to the beat under a warm lamp.',
    settings: {
      globalSpeed: 0.0084,
      surge: 0.18,
      layerCount: 2,
      blendMode: 'overlay',
      gooeyEffect: 0.75,
      rotationSpeed: 0.005,
      centerGravity: 0.35,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#220044',
      ledSpeed: 0.0,
      diffusionRate: 0.00006,
      buoyancy: 0.3,
      advection: 0.2,
      damping: 0.992,
      heatDecay: 0.997,
      automateRate: 0.04,
      platePressure: 0.3,
      glassSmear: 0.25,
      rainDrip: 0.6,
      viscosity: 'thick',
      polarity: 0.9,
      evaporationRate: 0.003,
      airVelocity: 0.02,
      vibrationFrequency: 0.1,
      transmission: 0.9,
      lampWarmth: 0.25,
      audioMappings: {
        velocity: 'bass',
        density: 'bass',
        color: 'none',
        rotation: 'none',
      },
    }
  },
  {
    id: 'neon-coral-reef',
    name: 'Neon Coral Reef',
    description: 'A reaction grows coral across the glass: coral, teal and amber branches spread, fork and are carried off by the current.',
    settings: {
      globalSpeed: 0.0168,
      boundaryContrast: 0.5,
      beads: 0.3,
      surge: 0.5,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.55,
      rotationSpeed: 0.012,
      centerGravity: 0.0,
      ledPlatform: true,
      ledMode: 'single',
      ledSpeed: 0.0,
      diffusionRate: 0.0001,
      buoyancy: 0.45,
      advection: 0.4,
      damping: 0.978,
      heatDecay: 0.985,
      automateRate: 0.12,
      platePressure: 0.35,
      glassSmear: 0.45,
      rainDrip: 0.55,
      viscosity: 'thick',
      polarity: 0.75,
      evaporationRate: 0.012,
      airVelocity: 0.12,
      vibrationFrequency: 0.4,
      chemistry: 0.7,
      ledColor: '#021418',
      saturationBoost: 1.4,
      audioMappings: {
        velocity: 'mid',
        density: 'treble',
        color: 'complexity',
        rotation: 'timbre',
      },
    }
  },
  {
    id: 'stardust-collapse',
    name: 'Stardust Collapse',
    description: 'Motes of white, lavender and amber dust spiral into the centre and burst back out on the bass, every grain holding its colour.',
    settings: {
      globalSpeed: 0.0231,
      boundaryContrast: 0.65,
      beads: 0.3,
      surge: 0.85,
      layerCount: 2,
      blendMode: 'lighter',
      gooeyEffect: 0.05,
      rotationSpeed: 0.06,
      centerGravity: 0.95,
      // Glitter wants a night sky. On the rainbow wheel, with the dye dried
      // and diffused away, the frame was the wheel and nothing else.
      ledPlatform: false,
      ledMode: 'single',
      ledSpeed: 0.0,
      diffusionRate: 0.0002,     // a spark stays a spark
      buoyancy: 0.7,
      advection: 0.9,
      damping: 0.92,
      heatDecay: 0.93,
      automateRate: 0.22,
      platePressure: 0.85,
      glassSmear: 0.9,
      rainDrip: 0.15,
      viscosity: 'thin',
      polarity: 0.15,
      evaporationRate: 0.015,
      dyeBudget: 0.45,
      audioImpact: 0.85,
      airVelocity: 0.55,
      vibrationFrequency: 0.85,
      particles: 0.8,
      particleMix: 0.75,
      ledColor: '#000000',
      audioMappings: {
        velocity: 'bass',
        density: 'energy',
        color: 'treble',
        rotation: 'bass',
      },
    }
  },

  // ── Macro closeup presets ────────────────────────────────────────
  // These drive the tracking macro camera (macroMode). The frame rides one
  // bead of dye at high magnification, so the settings that matter most are
  // the ones that keep dye *separated* into distinct beads — high polarity,
  // low diffusion, low gooey blur — and fast enough to be worth chasing.
  {
    id: 'lumia',
    name: 'Lumia',
    description: 'Thomas Wilfred\u2019s aurora: slow folded sheets of light drifting under a nearly clear plate. No beat, no dye to speak of \u2014 minutes-long evolutions.',
    settings: {
      globalSpeed: 0.00504,
      surge: 0.12,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.5,
      rotationSpeed: 0.003,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#05030c',
      ledSpeed: 0.0,
      diffusionRate: 0.0002,
      buoyancy: 0.2,
      advection: 0.3,
      damping: 0.99,
      heatDecay: 0.99,
      automateRate: 0.008,
      platePressure: 0.05,
      glassSmear: 0.2,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.3,
      evaporationRate: 0.06,
      airVelocity: 0.02,
      vibrationFrequency: 0.0,
      audioImpact: 0.12,
      turbulenceScale: 0.12,
      turbulenceDetail: 2,
      blobSurfaceTension: 0.7,
      boundaryContrast: 0.15,
      saturationBoost: 1.2,
      dyeBudget: 0.1,          // a nearly clear plate: the light is the subject, the dye a few drifting veils
      edgeRelief: 0.3,
      bubbles: 0,
      plateRock: 0.1,
      layerScaleVariety: 0,
      lumia: 0.9,
      audioMappings: { velocity: 'energy', density: 'none', color: 'timbre', rotation: 'none' },
    }
  },
  {
    id: 'sensual-laboratory',
    name: 'Sensual Laboratory',
    description: 'Mark Boyle\u2019s London: reactions on the platen instead of oil in a dish. Coral and cells grow from the plate in graphite and rust, then the flow carries them off.',
    settings: {
      globalSpeed: 0.0126,
      surge: 0.3,
      layerCount: 1,
      blendMode: 'multiply',
      gooeyEffect: 0.4,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#f3ecdc',
      ledSpeed: 0.0,
      diffusionRate: 0.0002,
      buoyancy: 0.3,
      advection: 0.4,
      damping: 0.985,
      heatDecay: 0.985,
      automateRate: 0.03,
      platePressure: 0.2,
      glassSmear: 0.15,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.6,
      evaporationRate: 0.05,
      airVelocity: 0.03,
      vibrationFrequency: 0.0,
      audioImpact: 0.4,
      turbulenceScale: 0.15,
      turbulenceDetail: 3,
      blobSurfaceTension: 0.5,
      boundaryContrast: 0.5,
      saturationBoost: 1.0,
      dyeBudget: 0.35,
      edgeRelief: 0.7,
      bubbles: 0.2,
      plateRock: 0.15,
      layerScaleVariety: 0,
      chemistry: 0.85,
      exposure: 0.7,
      audioMappings: { velocity: 'mid', density: 'none', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'oil-wheel',
    name: 'Oil Wheel',
    description: 'An Optikinetics wheel warming under a 250 W lamp: yellows, greens and blues turning at half a revolution a minute, cells drifting on convection, no hands on it.',
    settings: {
      globalSpeed: 0.0084,
      surge: 0.35,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.7,
      rotationSpeed: 0.05,
      centerGravity: 0.15,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#3a2408',
      ledSpeed: 0.0,
      diffusionRate: 0.0002,
      buoyancy: 0.6,
      advection: 0.5,
      damping: 0.99,
      heatDecay: 0.995,
      automateRate: 0.05,
      platePressure: 0.25,
      glassSmear: 0.1,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.8,
      evaporationRate: 0.006,
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      audioImpact: 0.3,
      turbulenceScale: 0.1,
      turbulenceDetail: 2,
      blobSurfaceTension: 0.75,
      boundaryContrast: 0.5,
      saturationBoost: 1.3,
      glossiness: 0.15,
      dyeBudget: 0.75,
      edgeRelief: 0.55,
      bubbles: 0.17,
      plateRock: 0,
      layerScaleVariety: 0.35,
      lampWarmth: 0.75,
      lampHotspot: 0.6,
      lampMotion: 0.2,
      lightPlay: 0.7,
      gelWheel: 0.25,
      gelSpeed: 0.25,
      dishVignette: 0.7,
      spinDrag: 0.08,
      audioMappings: { velocity: 'none', density: 'bass', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'poster-1969',
    name: 'Poster, 1969',
    description: 'Two opaque dyes on a single plate, hard-edged and flat like a screen-printed Fillmore poster: orange against ultramarine, the colours that vibrate.',
    settings: {
      globalSpeed: 0.0126,
      surge: 0.55,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.6,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0.00005,
      buoyancy: 0.3,
      advection: 0.5,
      damping: 0.975,
      heatDecay: 0.98,
      automateRate: 0.1,
      platePressure: 0.5,
      glassSmear: 0.2,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 1.0,
      evaporationRate: 0.002,
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      audioImpact: 0.55,
      turbulenceScale: 0.35,
      turbulenceDetail: 2,
      blobSurfaceTension: 0.6,
      boundaryContrast: 0.9,
      saturationBoost: 1.6,
      glossiness: 0.0,
      postBlurRadius: 0.0,
      dyeBudget: 1.1,
      edgeRelief: 0.0,
      bubbles: 0.07,
      plateRock: 0.5,
      beatSqueeze: 0.7,
      layerScaleVariety: 0.0,
      hueJourney: 0,
      lightPlay: 0.15,
      lampHotspot: 0.1,
      iridescence: 0,
      secondLamp: 0,
      audioMappings: { velocity: 'bass', density: 'bass', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'oil-on-water',
    name: 'Oil on Water',
    description: 'The macro photograph: yellow oil on water over blue paper, packed fields of bubbles, satellite droplets on the glass, a softbox in every dome, shallow focus.',
    settings: {
      globalSpeed: 0.0084,
      surge: 0.45,
      blendMode: 'screen',
      gooeyEffect: 0.6,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0.00008,
      buoyancy: 0.3,
      advection: 0.5,
      damping: 0.98,
      heatDecay: 0.99,
      automateRate: 0.06,
      platePressure: 0.3,
      glassSmear: 0.1,
      rainDrip: 0.0,
      viscosity: 'thick',
      evaporationRate: 0.002,
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      turbulenceDetail: 2,
      glossiness: 0.0,
      postBlurRadius: 0.3,
      plateRock: 0.25,
      beatSqueeze: 0.3,
      layerScaleVariety: 0.0,
      renderStyle: 'photo',
      camera: 1,
      layerCount: 1,
      polarity: 0.6,
      audioImpact: 0.4,
      turbulenceScale: 0.2,
      blobSurfaceTension: 0.8,
      boundaryContrast: 0.3,
      saturationBoost: 1.25,
      dyeBudget: 0.45,
      edgeRelief: 0.5,
      bubbles: 0.45,
      paperA: '#3f86d1',
      paperB: '#8fcbef',
      lightPlay: 0.9,
      lampMotion: 0.3,
      lampHotspot: 0.5,
      secondLamp: 0,
      iridescence: 0.2,
      microDroplets: 0.7,
      thinFilm: 0.15,
      focus: 0.6,
      aperture: 0.55,
      bloom: 0.35,
      chromaticAberration: 0.35,
      refraction: 0.7,
      audioMappings: { velocity: 'mid', density: 'bass', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'colorful-cosmos',
    name: 'Colorful Cosmos',
    description: 'Big round drops over a warm gradient, each a shaded planet with a terminator: two lamps, deep focus fall-off, bloom in the highlights.',
    settings: {
      globalSpeed: 0.0084,
      surge: 0.45,
      blendMode: 'screen',
      gooeyEffect: 0.6,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0.00008,
      buoyancy: 0.3,
      advection: 0.5,
      damping: 0.98,
      heatDecay: 0.99,
      automateRate: 0.06,
      platePressure: 0.3,
      glassSmear: 0.1,
      rainDrip: 0.0,
      viscosity: 'thick',
      evaporationRate: 0.002,
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      turbulenceDetail: 2,
      glossiness: 0.0,
      postBlurRadius: 0.3,
      plateRock: 0.25,
      beatSqueeze: 0.3,
      layerScaleVariety: 0.0,
      renderStyle: 'photo',
      camera: 1,
      layerCount: 1,
      polarity: 0.7,
      audioImpact: 0.45,
      turbulenceScale: 0.12,
      blobSurfaceTension: 1.0,
      boundaryContrast: 0.2,
      saturationBoost: 1.3,
      dyeBudget: 0.35,
      edgeRelief: 0.6,
      bubbles: 0.35,
      paperA: '#2a9aa3',
      paperB: '#ff9a4a',
      lightPlay: 1.0,
      lampMotion: 0.4,
      lampHotspot: 0.6,
      secondLamp: 0.6,
      iridescence: 0.3,
      microDroplets: 0.35,
      thinFilm: 0.25,
      focus: 0.7,
      aperture: 0.75,
      bloom: 0.55,
      chromaticAberration: 0.4,
      refraction: 0.8,
      audioMappings: { velocity: 'bass', density: 'bass', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'sunny-side-up',
    name: 'Sunny Side Up',
    description: 'Thin sheets of oil over a hot orange backdrop, every edge running with interference colour; the polarised-light photograph.',
    settings: {
      globalSpeed: 0.0084,
      surge: 0.5,
      blendMode: 'screen',
      gooeyEffect: 0.6,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0.00008,
      buoyancy: 0.3,
      advection: 0.5,
      damping: 0.98,
      heatDecay: 0.99,
      automateRate: 0.06,
      platePressure: 0.3,
      glassSmear: 0.1,
      rainDrip: 0.0,
      viscosity: 'thick',
      evaporationRate: 0.002,
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      turbulenceDetail: 2,
      glossiness: 0.0,
      postBlurRadius: 0.3,
      plateRock: 0.25,
      beatSqueeze: 0.3,
      layerScaleVariety: 0.0,
      renderStyle: 'photo',
      camera: 1,
      layerCount: 2,
      polarity: 0.6,
      audioImpact: 0.5,
      turbulenceScale: 0.3,
      blobSurfaceTension: 0.5,
      boundaryContrast: 0.5,
      saturationBoost: 1.5,
      dyeBudget: 0.5,
      edgeRelief: 0.4,
      bubbles: 0.25,
      backgroundLoop: 0.6,
      paperA: '#ffb300',
      paperB: '#ff3d00',
      lightPlay: 0.8,
      lampMotion: 0.5,
      lampHotspot: 0.4,
      secondLamp: 0.3,
      iridescence: 0.9,
      microDroplets: 0.3,
      thinFilm: 1.0,
      focus: 0.4,
      aperture: 0.4,
      bloom: 0.3,
      chromaticAberration: 0.5,
      refraction: 0.6,
      audioMappings: { velocity: 'mid', density: 'bass', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'macro-bead',
    name: 'Macro Bead',
    description: 'The camera chases one travelling bead — teal, amber and coral on a deep sea-green ground — cells, lacing and razor edges filling the frame.',
    settings: {
      macroMode: true,
      macroZoom: 4.5,            // ~28 sim cells across — bead plus its surroundings
      macroChase: 0.55,          // a quick follow with a whip on each cut
      macroHold: 4.5,
      macroCells: 0.85,
      macroCellScale: 0.45,
      macroLacing: 0.7,
      macroDepth: 0.6,
      macroEdgeDetail: 0.75,
      macroRelief: 0.8,       // domed beads with wet highlights
      globalSpeed: 0.06,
      surge: 0.45,         // beads visibly travel — the whole point
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.12,         // almost no metaball blur — keeps beads crisp
      postBlurRadius: 0.1,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#04181a',
      ledSpeed: 0.0,
      diffusionRate: 0.00003,    // colors stay separate instead of muddying
      buoyancy: 0.35,
      advection: 0.6,
      damping: 0.985,
      heatDecay: 0.985,
      automateRate: 0.16,
      platePressure: 0.3,
      glassSmear: 0.2,
      rainDrip: 0.05,
      viscosity: 'thick',
      polarity: 0.9,             // strong immiscibility — hard color boundaries
      evaporationRate: 0.03,     // ground clears between beads instead of washing over
      airVelocity: 0.08,
      vibrationFrequency: 0.05,
      audioImpact: 0.5,
      turbulenceScale: 0.45,
      turbulenceDetail: 3,
      blobSurfaceTension: 0.55,
      bubbles: 0.12,
      layerScaleVariety: 0,
      boundaryContrast: 0.7,
      saturationBoost: 1.5,
      glossiness: 0.12,          // a hint of wet sheen at this distance
      macroSync: 0.6,
      audioMappings: {
        velocity: 'bass',
        density: 'volume',
        color: 'treble',
        rotation: 'none',
      },
    }
  },
  {
    id: 'cell-bloom',
    name: 'Cell Bloom',
    description: 'Packed rings of paint cells — dark cores in bright magenta and lavender halos — breathing across a magnified violet pool.',
    settings: {
      macroMode: true,
      macroZoom: 3.5,
      macroChase: 0.45,          // slower drift — this one lingers on a pool
      macroHold: 7.0,
      macroCells: 1.0,           // maximum cell structure
      macroCellScale: 0.32,      // small, densely packed cells
      macroLacing: 0.35,
      macroDepth: 0.7,
      macroEdgeDetail: 0.5,
      macroRelief: 0.9,       // deepest relief of the three — cells read as bubbles
      globalSpeed: 0.045,
      surge: 0.5,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.2,
      postBlurRadius: 0.12,
      rotationSpeed: 0.004,
      centerGravity: 0.05,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#12062a',
      ledSpeed: 0.0,
      diffusionRate: 0.00005,
      buoyancy: 0.5,
      advection: 0.45,
      damping: 0.99,
      heatDecay: 0.99,
      automateRate: 0.1,
      platePressure: 0.45,
      glassSmear: 0.25,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.85,
      evaporationRate: 0.02,
      airVelocity: 0.05,
      vibrationFrequency: 0.0,
      audioImpact: 0.55,
      turbulenceScale: 0.35,
      turbulenceDetail: 2,
      blobSurfaceTension: 0.6,
      bubbles: 0.1,
      layerScaleVariety: 0,
      boundaryContrast: 0.6,
      saturationBoost: 1.55,
      glossiness: 0.18,
      macroSync: 0.35,
      audioMappings: {
        velocity: 'mid',
        density: 'bass',
        color: 'treble',
        rotation: 'none',
      },
    }
  },
  {
    id: 'lace-run',
    name: 'Lacing Run',
    description: 'A tongue of amber dye spreading over dark red ground, dragging black dendritic lacing behind it; the camera cuts on the kick.',
    settings: {
      macroMode: true,
      macroZoom: 4.0,
      macroChase: 0.7,           // the liveliest of the three
      macroHold: 4.0,            // short takes
      macroCells: 0.8,
      macroCellScale: 0.55,
      macroLacing: 1.0,          // lacing is the subject here
      macroDepth: 0.6,
      macroEdgeDetail: 0.9,      // maximum silhouette crinkle
      macroRelief: 0.65,
      globalSpeed: 0.07,
      surge: 0.6,         // quick — this one rushes
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.08,
      postBlurRadius: 0.08,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#2E0705',
      ledSpeed: 0.0,
      diffusionRate: 0.00004,
      buoyancy: 0.3,
      advection: 0.85,
      damping: 0.975,
      heatDecay: 0.97,
      automateRate: 0.2,
      platePressure: 0.45,       // squeeze drives the front without flattening it
      glassSmear: 0.4,
      rainDrip: 0.2,
      viscosity: 'thin',
      polarity: 0.95,
      evaporationRate: 0.035,
      airVelocity: 0.2,
      vibrationFrequency: 0.1,
      audioImpact: 0.65,
      turbulenceScale: 0.7,
      turbulenceDetail: 4,
      blobSurfaceTension: 0.15,
      bubbles: 0.15,
      layerScaleVariety: 0,
      boundaryContrast: 0.8,
      saturationBoost: 1.4,
      glossiness: 0.08,
      macroSync: 0.85,
      audioMappings: {
        velocity: 'bass',
        density: 'energy',
        color: 'treble',
        rotation: 'none',
      },
    }
  },
  {
    id: 'fillmore-1969',
    name: 'Fillmore East, 1969',
    description: 'The Joshua Light Show behind the Mothers: three projectors on one black screen, a big dish pressed into a radial sunburst, a field of dark-rimmed oil beads across the red and orange, cyan and blue against them.',
    settings: {
      globalSpeed: 0.01008,
      surge: 0.6,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.5,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0,          // measured: sharper without it, and a pass cheaper
      buoyancy: 0.3,
      advection: 0.55,
      damping: 0.975,
      heatDecay: 0.98,
      automateRate: 0.12,
      platePressure: 0.6,
      glassSmear: 0.25,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 1.0,
      evaporationRate: 0.002,
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      audioImpact: 0.6,
      turbulenceScale: 0.3,
      turbulenceDetail: 2,
      blobSurfaceTension: 0.5,
      boundaryContrast: 0.05,
      saturationBoost: 1.55,
      glossiness: 0.0,
      postBlurRadius: 0.0,
      dyeBudget: 0.9,
      edgeRelief: 0.05,
      lacing: 0.55,
      bubbles: 0.1,
      beads: 0.8,
      fingering: 0.85,
      cells: 0.2,
      dishSpread: 0.85,
      dishVignette: 0.0,
      plateRock: 0.3,
      beatSqueeze: 0.9,
      layerScaleVariety: 0.0,
      backgroundLoop: 0.6,
      hueJourney: 4,
      lightPlay: 0.3,
      lampMotion: 0.2,
      lampHotspot: 0.6,
      lampWarmth: 0.2,
      iridescence: 0.1,
      secondLamp: 0.2,
      audioMappings: { velocity: 'bass', density: 'bass', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'crowd-plate',
    name: 'Crowd Plate',
    description: 'The room plays it: the floor stirs the liquid, everyone dancing is a hand on the glass, and a busier room opens the turbulence.',
    settings: {
      // A plate that wants stirring rather than one that is already busy: the
      // turbulence starts low so what the room adds is what is seen moving,
      // and the dye budget runs full so there is something there to move.
      globalSpeed: 0.0126,
      surge: 0.55,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.5,
      rotationSpeed: 0.0,
      centerGravity: 0.05,
      granulation: 0.5,
      diffusionRate: 0.00012,
      buoyancy: 0.3,
      advection: 0.45,
      damping: 0.985,
      heatDecay: 0.99,
      automateRate: 0.08,          // the room does the injecting; automation only tops it up
      platePressure: 0.35,
      glassSmear: 0.25,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.7,
      evaporationRate: 0.0025,
      audioImpact: 0.35,           // the music is still there, but it is not the loudest hand
      turbulenceScale: 0.12,
      turbulenceDetail: 2,
      blobSurfaceTension: 0.5,
      boundaryContrast: 0.1,
      saturationBoost: 1.45,
      dyeBudget: 1.0,
      edgeRelief: 0.15,
      bubbles: 0.15,
      beads: 0.2,
      fingering: 0.6,              // a palm on the glass breaks into spokes
      plateRock: 0.2,
      beatSqueeze: 0.5,
      lightPlay: 0.35,
      lampMotion: 0.25,
      lampHotspot: 0.5,
      hueJourney: 5,

      // The room, on.
      sceneDrive: 0.55,
      sceneHands: 0.6,
      sceneImpact: 0.6,
      sceneMappings: [
        // A fuller floor is a rougher plate, and a room that goes quiet
        // settles rather than stopping.
        { feature: 'motion', setting: 'turbulenceScale', depth: 0.45 },
        // The lamp walks with the crowd instead of sitting under the middle.
        { feature: 'dirX', setting: 'lampMotion', depth: 0.35 },
        // More people, more dye on the plate.
        { feature: 'crowd', setting: 'dyeBudget', depth: 0.25 },
      ],
      audioMappings: { velocity: 'bass', density: 'bass', color: 'treble', rotation: 'none' },
    }
  },

  // ── Three that could not exist before the liquids did ──────────────
  //
  // Every preset above is a set of numbers describing how the plate behaves.
  // These three are looks where the *liquid on the plate* is the subject, so
  // they lean on the soap, body and repel field rather than on the solver's
  // own tuning. Each is close to something a person can put on a table.
  {
    id: 'milk-marble',
    name: 'Milk Marbling',
    description: 'The kitchen-table experiment: four spots of food colouring sitting still on a dish of milk until a drop of soap sends them running for the rim.',
    settings: {
      // The dish does almost nothing on its own. Turbulence, buoyancy, heat
      // and rotation are all near zero, because if the plate is already
      // churning then the soap arriving is just one more thing moving. The
      // entire look is the contrast between a plate that is *dead still* and
      // the half second after the soap lands.
      globalSpeed: 0.0126,
      surge: 0.3,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.45,
      rotationSpeed: 0.0,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0.00004,      // near-zero: food colouring on milk does not bleed on its own
      buoyancy: 0.05,
      advection: 0.5,
      damping: 0.985,
      heatDecay: 0.995,
      automateRate: 0.07,          // a drop of soap now and then, not a stream of it
      platePressure: 0.1,
      glassSmear: 0.1,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.9,               // the colours stay four colours, not one brown one
      evaporationRate: 0.0015,     // the ground has to last; this is a long, slow dish
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      audioImpact: 0.3,            // the beat is when a drop lands, not a shove of its own
      turbulenceScale: 0.05,
      turbulenceDetail: 2,
      blobSurfaceTension: 0.7,
      boundaryContrast: 0.55,      // a bright line where a colour front meets the ground
      saturationBoost: 1.5,
      glossiness: 0.05,
      postBlurRadius: 0.1,
      dyeBudget: 1.0,
      edgeRelief: 0.3,
      bubbles: 0.0,
      plateRock: 0.1,
      beatSqueeze: 0.25,
      layerScaleVariety: 0.0,
      hueJourney: 0,               // four food colourings, and they stay those four
      lightPlay: 0.2,
      lampHotspot: 0.35,
      iridescence: 0,
      secondLamp: 0,
      audioMappings: { velocity: 'none', density: 'bass', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'soap-film',
    name: 'Soap Film',
    description: 'One sheet of interference colour, torn open again and again: each hole rushes outward, thins to a rim, and curls into filaments before the next one lands.',
    settings: {
      // Thin-film optics over a plate whose only event is the tear. The film
      // has to be thin for the colour to be there at all, which is also what
      // makes it easy to break — so evaporation runs high and the dye budget
      // low, and the soap keeps re-opening what the flow closes.
      globalSpeed: 0.0168,
      surge: 0.5,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.3,
      rotationSpeed: 0.004,
      centerGravity: 0.08,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0.00009,
      buoyancy: 0.2,
      advection: 0.6,              // the rush has to actually carry the dye
      damping: 0.982,
      heatDecay: 0.99,
      automateRate: 0.2,           // tears often — this is the one preset that wants soap
      platePressure: 0.2,
      glassSmear: 0.35,
      rainDrip: 0.0,
      viscosity: 'thin',
      polarity: 0.5,
      evaporationRate: 0.006,      // a film that is always thinning is always about to go
      airVelocity: 0.05,
      vibrationFrequency: 0.05,
      audioImpact: 0.5,
      turbulenceScale: 0.3,        // some vorticity, so the fronts curl instead of ringing
      turbulenceDetail: 3,
      blobSurfaceTension: 0.2,
      boundaryContrast: 0.7,       // the rim of a hole is the brightest thing in frame
      saturationBoost: 1.35,
      glossiness: 0.2,
      postBlurRadius: 0.2,
      dyeBudget: 0.5,
      edgeRelief: 0.55,
      bubbles: 0.05,
      plateRock: 0.25,
      beatSqueeze: 0.4,
      layerScaleVariety: 0.0,
      hueJourney: 7,
      lightPlay: 0.6,
      lampMotion: 0.2,
      lampHotspot: 0.45,
      iridescence: 0.75,           // the reason a soap film is worth looking at
      thinFilm: 0.8,
      secondLamp: 0,
      audioMappings: { velocity: 'mid', density: 'bass', color: 'treble', rotation: 'none' },
    }
  },
  {
    id: 'glycerine-drift',
    name: 'Glycerine Drift',
    description: 'Bands of deep dye drifting against each other, with thick patches that simply refuse to go along — the plate slides past them and shears.',
    settings: {
      // A plate with a real current in it and nothing to stop the current
      // except the glycerine itself. Damping and advection both run high so
      // the bands keep moving for minutes; what makes the picture is the
      // handful of places that do not move with them.
      globalSpeed: 0.0105,
      surge: 0.28,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.55,
      rotationSpeed: 0.006,
      centerGravity: 0.0,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0.0001,
      buoyancy: 0.15,              // sideways, not upward: this is shear, not convection
      advection: 0.7,
      damping: 0.992,              // the current has to survive long enough to shear something
      heatDecay: 0.994,
      automateRate: 0.1,
      platePressure: 0.15,
      glassSmear: 0.45,            // the smear reads as the drift
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.75,
      evaporationRate: 0.002,
      airVelocity: 0.08,
      vibrationFrequency: 0.0,
      audioImpact: 0.4,
      turbulenceScale: 0.18,       // low: a smooth current shows a stuck patch, a rough one hides it
      turbulenceDetail: 2,
      blobSurfaceTension: 0.45,
      boundaryContrast: 0.35,
      saturationBoost: 1.5,
      glossiness: 0.1,
      postBlurRadius: 0.25,
      dyeBudget: 0.9,
      edgeRelief: 0.35,
      bubbles: 0.05,
      plateRock: 0.45,             // the rock is what supplies the current
      beatSqueeze: 0.3,
      layerScaleVariety: 0.3,
      hueJourney: 9,
      lightPlay: 0.4,
      lampMotion: 0.35,
      lampHotspot: 0.4,
      iridescence: 0.1,
      secondLamp: 0.25,
      transmission: 0.8,
      audioMappings: { velocity: 'bass', density: 'mid', color: 'treble', rotation: 'none' },
    }
  },
  // ── Three that show off a part of the app ────────────────────────
  // The ferrofluid and its magnet, the film stock, and the curved glasses
  // were each built, measured and set by no preset at all, so nobody who
  // only picks looks had ever seen them.
  {
    id: 'magnet-garden',
    name: 'Magnet Garden',
    description: 'Black ferrofluid on a bright pool of amber, teal and ice, a magnet held under the glass: it gathers into spikes and labyrinths and lets go on the beat.',
    settings: {
      globalSpeed: 0.0105,
      surge: 0.35,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.55,
      rotationSpeed: 0.004,
      centerGravity: 0.2,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#1a1408',
      ledSpeed: 0.0,
      diffusionRate: 0,
      buoyancy: 0.25,
      advection: 0.35,
      damping: 0.985,
      heatDecay: 0.99,
      automateRate: 0.1,
      platePressure: 0.3,
      glassSmear: 0.2,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.8,
      evaporationRate: 0.003,
      airVelocity: 0.02,
      vibrationFrequency: 0.1,
      audioImpact: 0.5,
      blobSurfaceTension: 0.5,
      boundaryContrast: 0.3,
      saturationBoost: 1.4,
      dyeBudget: 1.0,
      glossiness: 0.2,
      postBlurRadius: 0.15,
      phaseAmount: 0.65,
      phaseScale: 0.3,
      phaseSharp: 0.75,
      magnetStrength: 0.7,
      magnetHeight: 0.3,
      magnetPolarity: 1,
      beatSqueeze: 0.4,
      lampHotspot: 0.4,
      secondLamp: 0.3,
      audioMappings: { velocity: 'bass', density: 'mid', color: 'none', rotation: 'none' },
    }
  },
  {
    id: 'home-movie',
    name: 'Home Movie',
    description: 'A light show filmed on Super 8 from the back of the hall: warm, soft, grainy, the gate weaving, orange and coral against teal.',
    settings: {
      globalSpeed: 0.0105,
      surge: 0.55,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.6,
      rotationSpeed: 0.01,
      centerGravity: 0.15,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0,
      buoyancy: 0.4,
      advection: 0.4,
      damping: 0.985,
      heatDecay: 0.99,
      automateRate: 0.14,
      platePressure: 0.35,
      glassSmear: 0.3,
      rainDrip: 0.1,
      viscosity: 'thick',
      polarity: 0.75,
      evaporationRate: 0.004,
      airVelocity: 0.04,
      vibrationFrequency: 0.1,
      audioImpact: 0.55,
      blobSurfaceTension: 0.4,
      boundaryContrast: 0.4,
      saturationBoost: 1.4,
      dyeBudget: 0.8,
      postBlurRadius: 0.3,
      stock: 0.85,
      stockType: 3,
      stockGrain: 0.6,
      stockWeave: 1.2,
      stockGate: 0.5,
      lampWarmth: 0.45,
      dishVignette: 0.3,
      hueJourney: 2,
      audioMappings: { velocity: 'bass', density: 'volume', color: 'treble', rotation: 'none' },
    }
  },
  {
    id: 'clock-glass',
    name: 'Clock Glass',
    description: 'Two curved clock glasses with the dye between them: ultramarine, amber and magenta pool in the deep middle, and a press leaves a thin bright film that creeps back.',
    settings: {
      globalSpeed: 0.0126,
      surge: 0.4,
      layerCount: 1,
      blendMode: 'screen',
      gooeyEffect: 0.5,
      rotationSpeed: 0.012,
      centerGravity: 0.1,
      ledPlatform: false,
      ledMode: 'single',
      ledColor: '#000000',
      ledSpeed: 0.0,
      diffusionRate: 0,
      buoyancy: 0.2,
      advection: 0.45,
      damping: 0.985,
      heatDecay: 0.99,
      automateRate: 0.12,
      platePressure: 0.55,
      glassSmear: 0.25,
      rainDrip: 0.0,
      viscosity: 'thick',
      polarity: 0.85,
      evaporationRate: 0.003,
      airVelocity: 0.02,
      vibrationFrequency: 0.05,
      audioImpact: 0.55,
      blobSurfaceTension: 0.45,
      boundaryContrast: 0.35,
      saturationBoost: 1.45,
      dyeBudget: 0.9,
      glossiness: 0.25,
      postBlurRadius: 0.15,
      plateCurve: 0.6,
      depthDrag: 1.5,
      plateSpring: 0.35,
      beatSqueeze: 0.6,
      transmission: 0.8,
      dishVignette: 0.8,
      lampHotspot: 0.5,
      audioMappings: { velocity: 'bass', density: 'bass', color: 'treble', rotation: 'none' },
    }
  },
];
