import { VisualizerSettings, AudioMappings } from './types';

export interface Preset {
  id: string;
  name: string;
  description: string;
  settings: Partial<VisualizerSettings>;
}

const DEFAULT_MAPPINGS: AudioMappings = {
  velocity: 'mid',
  density: 'bass',
  color: 'treble',
  rotation: 'none',
  bubbles: 'bass',
};

export const PRESETS: Preset[] = [
  {
    id: 'classic',
    name: 'Classic Light Show',
    description: 'The standard 1960s psychedelic liquid light show.',
    settings: {
      globalSpeed: 0.05,
      layerCount: 3,
      blendMode: 'screen',
      gooeyEffect: 0.4,
      rotationSpeed: 0.02,
      centerGravity: 0.2,
      ledPlatform: false,
      surfaceTension: 0.05,
      diffusionRate: 0.0001,
      buoyancy: 0.5,
      advection: 0.5,
      damping: 0.98,
      heatDecay: 0.95,
      automateRate: 0.1,
      bubbleAmount: 0.2,
      bubbleBaseSize: 12,
      bubbleSizeVariance: 8,
      platePressure: 0.3,
      glassSmear: 0.5,
      rainDrip: 0.5,
      viscosity: 'thick',
      polarity: 0.9,
      heatIntensity: 0.15,
      boilingPoint: 0.75,
      evaporationRate: 0.03,
      airVelocity: 0.1,
      vibrationFrequency: 0.5,
      audioMappings: { ...DEFAULT_MAPPINGS },
    }
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    description: 'Slow moving, dense fluids over a deep blue LED platform.',
    settings: {
      globalSpeed: 0.03,
      layerCount: 2,
      blendMode: 'overlay',
      gooeyEffect: 0.8,
      rotationSpeed: 0.01,
      centerGravity: 0.8,
      ledPlatform: true,
      ledMode: 'ocean',
      ledSpeed: 0.05,
      surfaceTension: 0.1,
      diffusionRate: 0.0001,
      buoyancy: 0.2,
      advection: 0.2,
      damping: 0.99,
      heatDecay: 0.98,
      automateRate: 0.05,
      bubbleAmount: 0.6,
      bubbleBaseSize: 20,
      bubbleSizeVariance: 15,
      platePressure: 0.1,
      glassSmear: 0.2,
      rainDrip: 0.8,
      viscosity: 'thick',
      polarity: 0.8,
      heatIntensity: 0.05,
      boilingPoint: 0.9,
      evaporationRate: 0.01,
      airVelocity: 0.05,
      vibrationFrequency: 0.2,
      audioMappings: {
        velocity: 'volume',
        density: 'bass',
        color: 'none',
        rotation: 'energy',
        bubbles: 'complexity',
      },
    }
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'High contrast, fast-moving neon fluids over a cyberpunk LED base.',
    settings: {
      globalSpeed: 0.08,
      layerCount: 4,
      blendMode: 'lighter',
      gooeyEffect: 0.1,
      rotationSpeed: 0.05,
      centerGravity: 0.5,
      ledPlatform: true,
      ledMode: 'cyberpunk',
      ledSpeed: 0.3,
      surfaceTension: 0.01,
      diffusionRate: 0.0005,
      buoyancy: 0.8,
      advection: 0.6,
      damping: 0.95,
      heatDecay: 0.9,
      automateRate: 0.2,
      bubbleAmount: 0.1,
      bubbleBaseSize: 6,
      bubbleSizeVariance: 4,
      platePressure: 0.6,
      glassSmear: 0.8,
      rainDrip: 0.2,
      viscosity: 'thin',
      polarity: 0.2,
      heatIntensity: 0.3,
      boilingPoint: 0.6,
      evaporationRate: 0.05,
      airVelocity: 0.3,
      vibrationFrequency: 0.8,
      audioMappings: {
        velocity: 'energy',
        density: 'treble',
        color: 'timbre',
        rotation: 'complexity',
        bubbles: 'mid',
      },
    }
  },
  {
    id: 'lava-lamp',
    name: 'Lava Lamp',
    description: 'Highly buoyant, gooey blobs rising over a warm fire LED.',
    settings: {
      globalSpeed: 0.04,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.9,
      rotationSpeed: 0.01,
      centerGravity: 0.1,
      ledPlatform: true,
      ledMode: 'fire',
      ledSpeed: 0.02,
      surfaceTension: 0.2,
      diffusionRate: 0.00005,
      buoyancy: 0.9,
      advection: 0.15,
      damping: 0.97,
      heatDecay: 0.99,
      automateRate: 0.1,
      bubbleAmount: 0.8,
      bubbleBaseSize: 25,
      bubbleSizeVariance: 20,
      platePressure: 0.2,
      glassSmear: 0.3,
      rainDrip: 0.1,
      viscosity: 'thick',
      polarity: 0.95,
      heatIntensity: 0.8,
      boilingPoint: 0.6,
      evaporationRate: 0.02,
      airVelocity: 0.05,
      vibrationFrequency: 0.1,
      audioMappings: {
        velocity: 'bass',
        density: 'volume',
        color: 'none',
        rotation: 'none',
        bubbles: 'energy',
      },
    }
  },
  {
    id: 'ink-bleed',
    name: 'Monochrome Ink',
    description: 'Sharp, high-contrast ink bleeding over a stark white backlight.',
    settings: {
      globalSpeed: 0.05,
      layerCount: 3,
      blendMode: 'multiply',
      gooeyEffect: 0.0,
      rotationSpeed: 0.0,
      centerGravity: 0.3,
      ledPlatform: true,
      ledMode: 'single',
      ledColor: '#ffffff',
      ledSpeed: 0.0,
      surfaceTension: 0.0,
      diffusionRate: 0.002,
      buoyancy: 0.4,
      advection: 0.4,
      damping: 0.96,
      heatDecay: 0.94,
      automateRate: 0.15,
      bubbleAmount: 0.0,
      bubbleBaseSize: 5,
      bubbleSizeVariance: 2,
      platePressure: 0.4,
      glassSmear: 0.1,
      rainDrip: 0.9,
      viscosity: 'thin',
      polarity: 0.1,
      heatIntensity: 0.1,
      boilingPoint: 0.8,
      evaporationRate: 0.08,
      airVelocity: 0.0,
      vibrationFrequency: 0.0,
      audioMappings: {
        velocity: 'complexity',
        density: 'energy',
        color: 'none',
        rotation: 'timbre',
        bubbles: 'none',
      },
    }
  },
  {
    id: 'acid-trip',
    name: 'Acid Trip',
    description: 'Chaotic, rapidly rotating colors with strange blending physics.',
    settings: {
      globalSpeed: 0.08,
      layerCount: 3,
      blendMode: 'exclusion',
      gooeyEffect: 0.5,
      rotationSpeed: 0.1,
      centerGravity: 0.6,
      ledPlatform: true,
      ledMode: 'rainbow',
      ledSpeed: 0.4,
      surfaceTension: 0.15,
      diffusionRate: 0.0002,
      buoyancy: 0.6,
      advection: 0.8,
      damping: 0.95,
      heatDecay: 0.97,
      automateRate: 0.25,
      bubbleAmount: 1.0,
      bubbleBaseSize: 15,
      bubbleSizeVariance: 10,
      platePressure: 0.8,
      glassSmear: 0.9,
      rainDrip: 0.4,
      viscosity: 'thin',
      polarity: 0.5,
      heatIntensity: 0.5,
      boilingPoint: 0.5,
      evaporationRate: 0.04,
      airVelocity: 0.5,
      vibrationFrequency: 0.9,
      audioMappings: {
        velocity: 'treble',
        density: 'timbre',
        color: 'complexity',
        rotation: 'energy',
        bubbles: 'volume',
      },
    }
  },
  {
    id: 'bass-drop',
    name: 'Bass Drop',
    description: 'Heavy bass hits trigger massive fluid injections and screen shakes.',
    settings: {
      globalSpeed: 0.05,
      layerCount: 2,
      blendMode: 'screen',
      gooeyEffect: 0.6,
      rotationSpeed: 0.01,
      centerGravity: 0.4,
      ledPlatform: false,
      surfaceTension: 0.08,
      diffusionRate: 0.0005,
      buoyancy: 0.3,
      advection: 0.5,
      damping: 0.94,
      heatDecay: 0.92,
      automateRate: 0.05,
      bubbleAmount: 0.5,
      bubbleBaseSize: 18,
      bubbleSizeVariance: 12,
      platePressure: 0.9,
      glassSmear: 0.7,
      rainDrip: 0.3,
      viscosity: 'thick',
      polarity: 0.7,
      heatIntensity: 0.2,
      boilingPoint: 0.8,
      evaporationRate: 0.02,
      airVelocity: 0.2,
      vibrationFrequency: 1.0,
      audioMappings: {
        velocity: 'bass',
        density: 'bass',
        color: 'none',
        rotation: 'none',
        bubbles: 'bass',
      },
    }
  },
  {
    id: 'timbre-shifter',
    name: 'Timbre Shifter',
    description: 'The brightness of the sound controls the color and rotation of the fluid.',
    settings: {
      globalSpeed: 0.06,
      layerCount: 3,
      blendMode: 'lighter',
      gooeyEffect: 0.3,
      rotationSpeed: 0.03,
      centerGravity: 0.5,
      ledPlatform: true,
      ledMode: 'rainbow',
      ledSpeed: 0.2,
      surfaceTension: 0.02,
      diffusionRate: 0.0001,
      buoyancy: 0.7,
      advection: 0.6,
      damping: 0.98,
      heatDecay: 0.96,
      automateRate: 0.15,
      bubbleAmount: 0.1,
      bubbleBaseSize: 8,
      bubbleSizeVariance: 4,
      platePressure: 0.4,
      glassSmear: 0.5,
      rainDrip: 0.6,
      viscosity: 'thin',
      polarity: 0.6,
      heatIntensity: 0.3,
      boilingPoint: 0.7,
      evaporationRate: 0.03,
      airVelocity: 0.1,
      vibrationFrequency: 0.4,
      audioMappings: {
        velocity: 'mid',
        density: 'volume',
        color: 'timbre',
        rotation: 'timbre',
        bubbles: 'none',
      },
    }
  },
  {
    id: 'boiling-point',
    name: 'Boiling Point',
    description: 'High heat and complexity create a chaotic, bubbling cauldron.',
    settings: {
      globalSpeed: 0.07,
      layerCount: 4,
      blendMode: 'overlay',
      gooeyEffect: 0.7,
      rotationSpeed: 0.02,
      centerGravity: 0.1,
      ledPlatform: true,
      ledMode: 'fire',
      ledSpeed: 0.3,
      surfaceTension: 0.1,
      diffusionRate: 0.001,
      buoyancy: 1.0,
      advection: 0.8,
      damping: 0.9,
      heatDecay: 0.99,
      automateRate: 0.2,
      bubbleAmount: 1.0,
      bubbleBaseSize: 10,
      bubbleSizeVariance: 8,
      platePressure: 0.5,
      glassSmear: 0.6,
      rainDrip: 0.7,
      viscosity: 'thin',
      polarity: 0.8,
      heatIntensity: 0.9,
      boilingPoint: 0.4,
      evaporationRate: 0.06,
      airVelocity: 0.4,
      vibrationFrequency: 0.7,
      audioMappings: {
        velocity: 'energy',
        density: 'complexity',
        color: 'treble',
        rotation: 'complexity',
        bubbles: 'complexity',
      },
    }
  },
  {
    id: 'microscopic-chaos',
    name: 'Microscopic Chaos',
    description: 'Extremely dense, high-contrast cellular bubbles resembling oil and water under a microscope.',
    settings: {
      globalSpeed: 0.04,
      layerCount: 4,
      blendMode: 'screen',
      gooeyEffect: 0.15, // Low gooey effect keeps bubbles distinct
      rotationSpeed: 0.01,
      centerGravity: 0.5,
      ledPlatform: true,
      ledMode: 'rainbow',
      ledSpeed: 0.08,
      surfaceTension: 0.25, // High surface tension for distinct droplets
      diffusionRate: 0.00005,
      buoyancy: 0.4,
      advection: 0.3,
      damping: 0.98,
      heatDecay: 0.95,
      automateRate: 0.3,
      bubbleAmount: 1.0, // Maximum bubbles
      bubbleBaseSize: 4, // Very small base size
      bubbleSizeVariance: 18, // High variance for mix of tiny and medium bubbles
      platePressure: 0.8,
      glassSmear: 0.2,
      rainDrip: 0.1,
      viscosity: 'thick',
      polarity: 0.95, // High repulsion
      heatIntensity: 0.2,
      boilingPoint: 0.8,
      evaporationRate: 0.01,
      airVelocity: 0.1,
      vibrationFrequency: 0.6,
      audioMappings: {
        velocity: 'complexity',
        density: 'energy',
        color: 'timbre',
        rotation: 'none',
        bubbles: 'volume',
      },
    }
  }
];
